language:
  - "python"
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
before_install:
  - "travis_retry pip install codecov coveralls codacy-coverage pytest pytest-cov pylint"
script:
  - "py.test --cov=./"
after_success:
  - "pylint intlife"
  - "coveralls"
  - "coverage xml && python-codacy-coverage -r coverage.xml"