language:
  - "python"
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
before_install:
  - "pip install codecov pytest pytest-cov pylint"
script:
  - "py.test --cov=./"
  - "pylint intlife"
after_success:
  - "codecov"